# Generated by Django 4.2.16 on 2024-10-14 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Bath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                ("expiration_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nearest_station", models.CharField(max_length=255)),
                ("walking_time", models.IntegerField(default=0)),
                ("address", models.CharField(max_length=255)),
                (
                    "operating_hours_remarks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSentoStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visit_count", models.PositiveIntegerField(default=0)),
                ("points", models.PositiveIntegerField(default=0)),
                ("last_visit_date", models.DateTimeField(blank=True, null=True)),
                (
                    "sento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.sento"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "mission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.mission"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHour",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "月曜日"),
                            (2, "火曜日"),
                            (3, "水曜日"),
                            (4, "木曜日"),
                            (5, "金曜日"),
                            (6, "土曜日"),
                            (7, "日曜日"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "sento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="apis.sento",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mission",
            name="sento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="missions",
                to="apis.sento",
            ),
        ),
        migrations.CreateModel(
            name="BathType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "白湯"),
                            (2, "薬湯"),
                            (3, "水風呂"),
                            (4, "天然温泉"),
                            (5, "あつ湯"),
                            (6, "ジェットバス"),
                            (7, "炭酸泉"),
                        ]
                    ),
                ),
                (
                    "bath",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.bath"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bath",
            name="sento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baths",
                to="apis.sento",
            ),
        ),
    ]
