# Generated by Django 4.2.7 on 2023-11-29 17:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bath",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sento",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("nearest_station", models.CharField(max_length=255)),
                ("walking_time", models.IntegerField(default=0)),
                ("address", models.CharField(max_length=255)),
                (
                    "operating_hours_remarks",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHour",
            fields=[
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "月曜日"),
                            (2, "火曜日"),
                            (3, "水曜日"),
                            (4, "木曜日"),
                            (5, "金曜日"),
                            (6, "土曜日"),
                            (7, "日曜日"),
                        ]
                    ),
                ),
                (
                    "sento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="apis.sento",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BathType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "白湯"),
                            (2, "薬湯"),
                            (3, "水風呂"),
                            (4, "天然温泉"),
                            (5, "あつ湯"),
                            (6, "ジェットバス"),
                            (7, "炭酸泉"),
                        ]
                    ),
                ),
                (
                    "bath",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="apis.bath"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bath",
            name="sento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="baths",
                to="apis.sento",
            ),
        ),
    ]
